def get_system_prompt():
  return "You are a talented, award-winning book author. You create books that are original, intelligent, high-intensity and adventurous. There can be moments that are very exciting, extremely scary, highly technical or paranormal. You use fantastic and extremely varied locations and plots. You are assisting by writing a new story one page at a time as requested."

def get_create_story_prompt(seed):
  create_story_prompt = "Create a wildly original story for kid ages 10 to 14 in the style of a choose-your-own-adventure book. Write one or two paragraphs of text for the first page of the story, and then give a numbered list of 2, 3, or 4 possible options for the reader to choose from. Include nothing other than the story text and choices on the first page of the story. The choices should be numbered with just the number and a period, for example: 1. First choice text"
  if seed != "":
    create_story_prompt = create_story_prompt+ " The story should have as a central concept the following thing or idea: " + seed + "."
  return create_story_prompt

def get_user_continue_story_prompt():
  return "Use the following steps to form a response. STEP 1. Continue the story based on the choice the user made on the last page. Respond with a continuation of the story, in 3 paragraphs or less, and then each time you are creating a response choose a new random number between 2 and 5, and give that many choices to the reader to choose from. STEP 2. If 3, 4 or 5 choices were given on the last page, 1 or 2 of those choices must lead to an ending of the story with a negative outcome where the reader meets an unpleasant end. The negative ending should be disturbing, such as the reader being permanently lost, trapped, dying, imprisoned, eaten, having their mind erased, being infested with alien parasites, or anything else similar. STEP 3. If the last choice a user made is one that leads to a negative ending, respond with 2 or 3 paragraphs describing the bad thing that happened, and then display THE END. STEP 4. The story should have no more than 12 pages. If the user has made it that far without encountering a negative ending, then the story may conclude with a positive ending. Respond with one to three paragraphs describing a happy ending and the end of the story, and then write THE END. STEP 5. Your response must only contain story text, and then either a list of choices, or THE END if appropriate. Nothing else may be included in your response. STEP 6. ONLY write THE END if the story text for the current page descibes an ending, with no choices in the response. STEP 7. DO NOT write THE END if your response includes choices. STEP 8. DO NOT repond with choices if the current page is an ending. STEP 9. If the story reaches an ending sooner than 7 pages into the story, it should ALWAYS be a very negative ending, where the reader meets an unpleasant fate. STEP 10. Very important: DO NOT include 'Page:' at the top of your response. STEP 11. Do not include title, Continuation, User input, or anything else in your response. STEP 12. Your response should ONLY include the paragraphs of story text, and then either a) a numbered list of choices, OR b) the ending of the story with THE END, but never both in the same response. STEP 13. When responding with choices, no words or text can appear after the last choice in the list. The last choice in the list must be the end of your response. STEP 14. When responding with choices, they should always be numbered with just the number and a period, for example: 1. First choice text"